spring:
  redis:
    database: 0
    host: 192.168.44.128
    port: 6380
    lettuce:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 5000
    password:
server:
  port: 8080