server:
  port: 8001
spring:
  application:
    name: rabbitmq-consumer
  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: 192.168.44.132 # RabbitMQ 服务的地址
    port: 5672 # RabbitMQ 服务的端口
    username: lvchao # RabbitMQ 服务的账号
    password: lvchao # RabbitMQ 服务的密码
    publisher-confirm-type: correlated # 设置 Confirm 类型为 CORRELATED 。
    publisher-returns: true #
    virtual-host: /lc
    template:
      mandatory: true #设置为 true 后 消费者在消息没有被路由到合适队列情况下会被return监听，而不会自动删除

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lvchaoloving?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lvchao.rabbitmq.entity
  #configuration:
   # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: error