server:
  port: 8005
spring:
  application:
    name: rabbitmq-consumer
  # RabbitMQ 配置项，对应 RabbitProperties 配置类
  rabbitmq:
    host: 192.168.44.129 # RabbitMQ 服务的地址
    port: 5672 # RabbitMQ 服务的端口
    username: lvchao # RabbitMQ 服务的账号
    password: lvchao # RabbitMQ 服务的密码
    virtual-host: /lc
    listener:
      simple:
        concurrency: 5
        acknowledge-mode: manual  # manual:手动 ack（确认）
        max-concurrency: 10
        prefetch: 1

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lvchaoloving?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.lvchao.rabbitmq.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
