server:
  port: 8889
spring:
  application:
    name: knife4j-study
# knife4j安全配置
knife4j:
  production: true #false代表当前环境文档可用，true代表当前环境文档不可用
  basic:
    enable: true #false代表当前环境文档不受账号密码限制，true代表当前环境文档查看需要账号密码登录
    username: 123456
    password: 123456
